# This is a generated file. Not intended for manual editing.
services:
  eventedsserver:
    build:
      context: "C:\\Users\\canno\\RiderProjects\\EventEds"
      dockerfile: "EventEdsServer/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/EventEdsServer.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "eventedsserver:dev"
    ports: []
    volumes:
    - "C:\\Users\\canno\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\canno\\RiderProjects\\EventEds\\EventEdsServer:/app:rw"
    - "C:\\Users\\canno\\RiderProjects\\EventEds:/src:rw"
    working_dir: "/app"
